require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
    - db/schema.rb

Metrics/MethodLength:
  CountAsOne: [hash, array, heredoc]
  Exclude:
    - db/migrate/*.rb

RSpec/ExampleLength:
  CountAsOne: [hash, array]
  Max: 7 # MultipleExpectations + 2

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Rails/NotNullColumn:
  Enabled: false

Layout/LineLength:
  Exclude:
    - db/migrate/*.rb
