version: "3"
services:
  client:
    command: >
      bash -c 'npm run build && npm run test:e2e:ci'
    depends_on:
      api:
        condition: "service_healthy"
    environment:
      - CI=1
    volumes:
      - ./tests-outputs:/usr/src/app/test-results
