version: "3"
services:
  api:
    build: .
    platform: linux/x86_64
    entrypoint: bin/docker-entrypoint
    command: sh -c "bundle exec rails s -b '0.0.0.0'"
    depends_on:
      - "redis"
    links:
      - "redis:redis"
    volumes:
      - ./:/usr/src/app
    ports:
      - 3009:3000

  redis:
    image: redis:6
    command: --port 6382
