default: &default
  adapter: "mysql2"
  encoding: "utf8"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  socket: <%= ENV.fetch("DB_SOCKET", "/tmp/mysql.sock") %>

development:
  <<: *default
  database: <%= ENV.fetch("SERVICE_NAME").underscore %>_development

test:
  <<: *default
  database: <%= ENV.fetch("SERVICE_NAME").underscore %>_test

production:
  <<: *default
  database: <%= ENV.fetch("SERVICE_NAME").underscore %>_production
