name: Tests
on: [push]
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_RW_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_RW_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Start docker compose
        run: docker compose up -d

      - name: Run tests
        run: >
          ./bin/wait-for-it.sh localhost:3007 &&
          docker compose exec api bundle exec rspec
          --format progress
          --format RspecJunitFormatter
          --out rspec.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "./rspec.xml"

      - name: Publish documentation
        uses: actions/upload-artifact@v3
        with:
          name: schema.yml
          path: public/schema.yml

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Check coverage
        uses: vigetlabs/simplecov-check@1.0
        with:
          minimum_coverage: 100
          coverage_path: coverage/.last_run.json
